name: blincar_app
description: "Aplicación móvil Blincar - Transporte seguro"
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  camera: ^0.10.5+9
  centered_singlechildscrollview: ^0.2.0
  cloud_firestore: 5.6.12
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  firebase_crashlytics: ^4.0.0
  firebase_analytics: ^11.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.2
  flutter_stripe: ^11.4.0
  flutter_svg: ^2.2.0
  flutter_vlc_player: ^7.4.0
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^10.1.0
  get_it: ^7.6.9
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  share_plus: ^10.0.3
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^6.1.0
  url_launcher: ^6.3.1
  video_player: ^2.9.1

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.1

flutter_launcher_icons:
  remove_alpha_ios: true
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/b-icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/b-icon.png"
    background_color: "#1a1a2e"
    theme_color: "#4f46e5"
  windows:
    generate: true
    image_path: "assets/icons/b-icon.png"
    icon_size: 48

flutter_native_splash:
  color: "#1a1a1a"
  image: assets/images/b-splash.png
  branding: assets/images/b-logo-branding.png
  color_dark: "#1a1a1a"
  image_dark: assets/images/w-splash.png
  branding_dark: assets/images/w-logo-branding.png
  android_12:
    image: assets/images/b-logo-branding.png
    image_dark: assets/images/w-logo-branding.png
    icon_background_color_dark: "#1a1a1a"
  web: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/video/
    - firebase_seed_data.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Black.ttf
